// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIsXPHsKBECGDACPAf8j7AMnRcLvRdTjU',
    appId: '1:784804907672:web:9f2ef0a13ccf31a4271eed',
    messagingSenderId: '784804907672',
    projectId: 'garage-sale-kab',
    authDomain: 'garage-sale-kab.firebaseapp.com',
    storageBucket: 'garage-sale-kab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuB-GoQX5yxoY0xQAMqeCFOvgCo_5l2VQ',
    appId: '1:784804907672:android:a4e3b3cf93b2506c271eed',
    messagingSenderId: '784804907672',
    projectId: 'garage-sale-kab',
    storageBucket: 'garage-sale-kab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE1JUYuV_I-pul8bVNou6OllITXSUwE8g',
    appId: '1:784804907672:ios:288843563b73c8a3271eed',
    messagingSenderId: '784804907672',
    projectId: 'garage-sale-kab',
    storageBucket: 'garage-sale-kab.firebasestorage.app',
    iosBundleId: 'com.example.test2GaragesaleKayleb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE1JUYuV_I-pul8bVNou6OllITXSUwE8g',
    appId: '1:784804907672:ios:288843563b73c8a3271eed',
    messagingSenderId: '784804907672',
    projectId: 'garage-sale-kab',
    storageBucket: 'garage-sale-kab.firebasestorage.app',
    iosBundleId: 'com.example.test2GaragesaleKayleb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIsXPHsKBECGDACPAf8j7AMnRcLvRdTjU',
    appId: '1:784804907672:web:7af7faf0c628be5f271eed',
    messagingSenderId: '784804907672',
    projectId: 'garage-sale-kab',
    authDomain: 'garage-sale-kab.firebaseapp.com',
    storageBucket: 'garage-sale-kab.firebasestorage.app',
  );
}
